### ISSUE TITLE
Enable scheduling for B151 on production

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#109]
This must be done be tomorrow!

**Comment by jirutka** [comment]
And also deploy the current master to production, so we can switch fittable to production instance.

**Comment by jirutka** [comment]
Eh, we can’t switch fittable to production because of temporary search API. So please enable scheduling for B151 even on dev.

**Comment by flexik** [comment]
I have added FIT semester B151 on staging and production together with some schedule exceptions. I have not yet created semester B151 for FEL, because I have to make sure that everything works OK with their semester start on Thursday (1. 10.).

**Comment by jirutka** [comment]
Why you didn’t add all schedule exceptions except the one that is currently not supported by Sirius?!

**Comment by flexik** [comment]
Well, I have done that that. Did I forget about some exceptions?

**Comment by jirutka** [comment]
Well, it seems there are actually two exceptions that we can’t support now?

* 28. 10. 2015 (státní svátek, středa – sudý  týden) – **náhrada dne 21. 12. 2015** (výuka jako v sudou 
středu)
* 17. 11. 2015 (státní svátek, úterý – lichý týden) – **náhrada 22. 12. 2015** (výuka jako v liché úterý)

**Comment by flexik** [comment]
Yes, these two and the parity change to the last week of the semester.

**Comment by jirutka** [comment]
Ah, okay.
