### ISSUE TITLE
Character encoding is broken

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#126]
![](https://cloud.githubusercontent.com/assets/616767/8736449/d51ec214-2c18-11e5-8a8d-eb7873213489.png)

**Comment by jirutka** [comment]
No, it’s not broken per se. You just have wrong default encoding in your browser and well, Sirius apparently doesn’t send charset in `Content-Type` header. It should send `Content-Type: application/json;charset=utf-8`.

**Comment by jnv** [comment]
Shouldn't rely on defaults, not?

**Comment by jirutka** [comment]
Yeah, it should send charset in the `Content-Type` header. However, what the heck do you have as a default encoding in your browser? :P

**Comment by jnv** [comment]
CP 1252 for whatever the damn reason. But I'd say ISO 8859-1 and CP 1250 will be more common defaults.

**Comment by jirutka** [comment]
Hello, we’re in 21st century, the age of Unicode! ISO 8859-1 and CP 1250 are damn bad defaults.

**Comment by jnv** [comment]
Tell me about it.
