### ISSUE TITLE
Expose iCalendar token through API

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#131]
In order to show link to iCalendar in clients like Fittable we need to somehow expose the access token.

However we need to figure authorisation model first. The easiest way is to expose local tokens. Perhaps we might want to introduce a new scope for ICS access-only, but I don't see much benefit in that.

Refs cvut/fittable-widget#51, cvut/fittable-widget#60

We may want to consider to introduce some general token / user / permissions endpoint, which would also allow to check for user's authorisation state.

**Comment by jirutka** [comment]
We don’t need any additional scope, `urn:ctu:oauth:sirius:personal:read` is well suitable for this – it should authorize user to read her own local access token.

**Comment by jnv** [comment]
Agreed. However I'm not sure how we could handle OAuth tokens within existing OAuth client?
Think about Fittable: in order to access all timetables, you will authorise and get an access with all scopes Fittable needs. But you would need to undergo a separate authorisation to get a limited access token for ICS access, am I right?
Furthermore it's not clear to me how you could reset the access token, but perhaps that's not so important.

We will use the local access tokens for the time being since the same issue applies even to non-interactive clients like batch scripts etc.

**Comment by jirutka** [comment]
> Think about Fittable: in order to access all timetables, you will authorise and get an access with all scopes Fittable needs.

That’s not true. Fittable uses authorization code grant, so each token is associated with the user who authorized it. We use scopes `urn:ctu:oauth:sirius:limited-by-idm:read` and `urn:ctu:oauth:sirius:personal:read` here.

> But you would need to undergo a separate authorisation to get a limited access token for ICS access, am I right?

Nope.

> …how you could reset the access token…

Currently you can’t, but that’s not a big deal IMO.

**Comment by MMajko** [comment]
Any progress with this one? :)

**Comment by jnv** [comment]
OK, this is now live on staging. Blocked for production until morale improves and PostgreSQL gets upgraded to 9.4.
