### ISSUE TITLE
Testing: Specify custom OAuth scopes in integration specs

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#137]
Shared context `authenticated via oauth` authorizes client against auth server with all client's scopes. Specs should be allowed to specify a subset of scopes for authorization and VCR tapes should be recorded separately for each set of scopes.

**Comment by jnv** [comment]
I guess we could mock `request_token_info` as in the spec for `RemoteOAuthServer` strategy, though it will be a bit dirty.

**Comment by flexik** [comment]
I have done it in https://github.com/cvut/sirius/commit/eaf9d02ff7349d91ba3fe3a85d5dac7a2acc33e0#diff-8ce07b4aa397758e13374fd46febbdb2R48. Though this is a bit dirty it removes external dependency on live OAAS server, so it is better than nothing.
