### ISSUE TITLE
Import “teacher’s timetable slots” (aka Tutor's time restriction)

### ISSUE THREAD

**Issue by hroncok** [cvut/sirius#142]
*Tutor's time restriction* is a feature form KOS allowing the teacher to set his/her own time slots to timetable. It's accessible from the *Other* menu.

![restriction](https://cloud.githubusercontent.com/assets/2401856/10055576/4ca62620-6237-11e5-93e2-997b4f3c3576.png)

Old timetable displayed that info, see [timetable of Karel Klouda](https://timetable.fit.cvut.cz/archive/B142/public/cz/ucitele/30/88/u308848000.html):

![klouda-rozvrh](https://cloud.githubusercontent.com/assets/2401856/10055615/886490c0-6237-11e5-846a-cfcd4152ea60.png)

This info is now not shown by sirius and fittable.

**Comment by jirutka** [comment]
Klouďák rulezz! :smile_cat:

**Comment by jirutka** [comment]
This is already done (#181). 😸 You can currently try it on dev version of fittable; [example](https://sirius.fit.cvut.cz/fittable-dev/people/kalvotom).
