### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#143]
This is tracking issue for errors in data reported by users. Most of them will be probably related to #90.

**Comment by jirutka** [comment]
proksmic teaches BI-CAO on Monday, 7.30 (680711423105) and 9.15 (680711424705). These parallels do exist in Sirius, but with no teacher. According to data from KOSapi these parallels was updated at 2015-09-23 23:46, so it should be already updated in Sirius.

RT 8420

/cc @flexik

**Comment by jirutka** [comment]
Parallels of MI-PPR.2 and MIE-PPR.2 (all taught by soch) are messed. Compare [old timetable](https://timetable.fit.cvut.cz/old/public/cz/ucitele/32/66/u32666000.html) and [fittable](https://timetable.fit.cvut.cz/new/people/soch).

* MI-PPR.2, par. 101 in odd week 7.30 no longer exist
* MI-PPR.2, par. 107 in even week 7.30 no longer exist
* MIE-PPR.2, par. 101 in odd week 16.15 no longer exist
* MIE-PPR.2, par. 101 in even week 16.15 should be in even week 7.30
* MIE-PPR.2, par. 102 in even week 7.30 is missing in Sirius

(All the parallels are at Tuesday)

**Comment by jirutka** [comment]
BI-AAG, par. 206 on Monday 16.15 (guthondr) doesn’t exist anymore.

RT 8411

**Comment by jnv** [comment]
From @kalvotom

> I was browsing through KAM courses and I it seems to me there are many errors and inconsistencies in the data. For example:
>
> MI-MPI timetable shows 12 paralles, but there should be only 9 of them. Paralles with ids 8, 11 are already deleted and 2 was moved to monday.
>
> Similar situation is in BI-ZMA (look at the thursday evening and last paralles on friday) and BI-PST (thursday evening). New timetable shows 21 paralles for BI-ZDM but only 14 of them really exist!
>
> In BI-MLO there is opposite problem. An existing parallel (id 108, thuesday 14:30) is not shown by the new timetable.

**Comment by jirutka** [comment]
We can breathe a sigh, all errors in data are finally fixed (by #144 and #148)! :smile_cat:
I’ve checked all the parallels mentioned in this issue and all are correct now.

**Comment by jnv** [comment]
I'm reopening this for further reports.

**Comment by jnv** [comment]
On production database, teching in the current semester for FIT ends on January 11th, which is incorrect. I will fix the database manually.

**Comment by jirutka** [comment]
This is already fixed.
