### ISSUE TITLE
Shorten synchronisation periods

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#147]
Since we now show data through Fittable, there is a demand for keeping data more up-to-date.

Ideally we should update data at least every hour.

We need to figure out how to split up the synchronisation process into smaller pieces and narrower scope – e.g. extracting students into the `people` table is not needed, but synchronising people in individual parallels is. Furthermore we want to focus only on the current semester.

@flexik Any ideas?

**Comment by jirutka** [comment]
Synchronization takes about 20 minutes now, so I shortened the period to every two hours.

**Comment by flexik** [comment]
Synchronization periods are shortened and it works fine so I am closing this.
