### ISSUE TITLE
Rewrite specs for UmapiClient

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#156]
No, @flexik, it’s really not okay to test against real roles of a real person in production Umapi…

[spec/lib/sirius_api/umapi_client_spec.rb](https://github.com/cvut/sirius/blob/c6ad47a11d22926be335df9134a7a7f5267c95dc/spec/lib/sirius_api/umapi_client_spec.rb)

**Comment by flexik** [comment]
Done in #167.
