### ISSUE TITLE
Show a user friendly error when user denies the permission request

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#158]
Currently 401 error is displayed.

**Comment by jirutka** [comment]
Well, we need to create an error page with its own URI, then I can set error handler for 401 in nginx. This page can be either plain HTML page, or an error screen in fittable with permanent link.

**Comment by jirutka** [comment]
Wait a moment, what’s this issue doing in Sirius repo?! This should be in fittable.

**Comment by jnv** [comment]
Dammit, got a wrong tab. I'll add it there.
