### ISSUE TITLE
Renew access token when Umapi returns 401

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#161]
When resource provider returns 401, it usually means that an access token has expired and you must obtain a new one. We’re not doing it now… or to be more specific, [oauth2](https://github.com/intridea/oauth2) gem is not doing it. We rely solely on `expires_in` attribute (number of seconds to expiration), but this is not 100% reliable (think about delays on network etc).

BTW, I think that we should look at a better oauth gem, [oauth2](https://github.com/intridea/oauth2) is not very good.

**Comment by flexik** [comment]
oauth2 gem is not geat, but only other one I found was [oauth2-ruby](https://github.com/aflatter/oauth2-ruby), which seems completely unfinished and dead.

**Comment by jnv** [comment]
Can't we treat this transparently on HTTP level, say, with [a middleware for Faraday](https://github.com/lostisland/faraday_middleware)?

**Comment by jirutka** [comment]
This would be ideal.

**Comment by jnv** [comment]
Otherwise there are 30 PRs for OAuth2, so it's fair to treat it dead as well. Perhaps we should look for active forks like [this one](https://github.com/motionauth/oauth2).

**Comment by flexik** [comment]
Handling it as a Faraday middleware wouldn't be bad. There is already [OAuth2 middleware](https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/request/oauth2.rb), but it is pretty simple. It just adds token to header and query parameters.

**Comment by jnv** [comment]
How 'bout this fella: https://github.com/google/signet

**Comment by jnv** [comment]
There's also this one: https://github.com/nov/rack-oauth2
Contrary to its name, it has a client implementation too.

**Comment by jirutka** [comment]
> How 'bout this fella: https://github.com/google/signet

Definitely not, look at the source code. This wrote some Java guy who saw Ruby for the first time…
