### ISSUE TITLE
Mark teaching ‘microperiods’ as exceptional

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#172]
While implementing mapping of periods to calendar weeks, we have realised that we cannot unambiguously define week's overal parity.

Consider a week with 4 teaching periods:

- two periods are have odd parity,
- two periods are even

What is the overall parity of the week?

We can identify one-day periods and ignore them, consider them as exceptional, but it is an arbitrary decision on our side. However there is a domain knowledge whether this exception is permanent; perhaps these exceptional periods should be marked as such?

**Comment by flexik** [comment]
I suggest we introduce period attribute `special`, which would indicate that a period is not a regular one. For now it can be automatically inferred from `first_day_override` - if it's set, then period is special, otherwise it is non-special.

On the other hand two or more non-special periods in a single week should always have the same parity, so figuring overall parity of the week should be easy if special periods are separated.

**Comment by jnv** [comment]
I agree with this solution, having an extra property which is only inferred from `first_day_override` adds almost none complexity but allows clients rely on this attribute.

@jirutka Are we clear on this?

**Comment by jirutka** [comment]
> two or more non-special periods in a single week should always have the same parity

I'm afraid that this assumption is wrong.

**Comment by jirutka** [comment]
I’m not happy with the name `special`. I suggest invert the meaning and name it `regular`. WDYT?

**Comment by jnv** [comment]
I would prefer if exceptional periods were marked so instead of the opposite, since we may introduce other period types in future where regular/irregular makes no sense. But I don't have a strong feeling about this.

**Comment by jirutka** [comment]
Well, so what about "irregular"? :P

**Comment by jnv** [comment]
I would like @flexik to have final say in this. We have settled on not using `exception*` since this is already overloaded. `special` is rather strange, but I don't mind it; `irregular` is prone to typos but I like it.

**Comment by jirutka** [comment]
@flexik, please give your final word about this.

* irregular
* regular
* special
* any else?

**Comment by flexik** [comment]
I am definitely for marking exceptional periods, not the other way around. As for naming, `irregular` seems more descriptive than `special`, so I would choose `irregular`.

**Comment by jnv** [comment]
I agree with @flexik on this one.

**Comment by jirutka** [comment]
Fixed by #175.
