### ISSUE TITLE
Missing MI-PAP tutorial on 2016-04-11

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#177]
See: https://timetable.fit.cvut.cz/new/courses/MI-PAP?date=2016-04-11

There should be a regular tutorial from 11.00 to 12.30, like in the other weeks, but it is completely missing. Could be either scheduling error or an incomplete scheduling cycle?

This issue was reported by the teacher Ivan Šimeček (xsimecek).

**Comment by jnv** [comment]
This is likely caused by the scheduling exception on 2016-04-04, but it is strange it has the prolonged impact on the next week.

**Comment by jirutka** [comment]
@flexik, could you please take a look at this ASAP?

**Comment by jnv** [comment]
:+1: from @petrpulc, on MI-MAI: https://sirius.fit.cvut.cz/fittable-dev/courses/MI-MAI?date=2016-04-11
It's the same date, by the way.
