### ISSUE TITLE
Use PostgreSQL’s “upsert” for great good

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#178]
We have already PostgreSQL 9.5 on dev and I’m gonna migrate production tonight. Thus we can take advantage of new [ON CONFLICT clause](http://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT) to simplify and speed-up synchronization process in Sirius.

**Comment by flexik** [comment]
This is worked on in PR #186.

**Comment by jirutka** [comment]
This is already implemented and merged (#209).
