### ISSUE TITLE
Order events

### ISSUE THREAD

**Issue by balakzde** [cvut/sirius#188]
/people/{username}/events
It would be nice to have the option of sorting event by start date. If I try to get 4 following events for user, I can't find a way how to properly do it.

**Comment by jnv** [comment]
Good idea. I guess we could add GET parameter `sort` which would accept e.g. `date` for ASC and `-date` for DESC ordering.

**Comment by jirutka** [comment]
Agree. Could you please implement it? Or @flexik? I'm currently very busy with ops. :(
