### ISSUE TITLE
Versioned / portable semester specification

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#197]
Currently the semester specifications, including exceptions, exists only in the production DB.

This means when you need to bootstrap development database, you are stuck with outdated seeds and outdated semesters, which makes external development and debugging harder, since the local configuration is vastly different from production environment.

I propose to add some function, perhaps Rake task, to dump semester and exceptions specifications from production DB into versioned YAML file, which can be used to locally seed the database. While this is a manual process, it is better than the current state.

Alternatively this could be a one-way process, having versioned semester specs, which will get imported into DB upon deployment, making maintenance more transparent.

**Comment by jirutka** [comment]
What about simple SQL dump instead of YAML?

**Comment by jnv** [comment]
Yeah, might be. I think the first step would be to provide some scripts to easily clone production DB.

Then if it is easy to do, we could keep some subset of dumps versioned – or just provide a separate scripts for that, since pg_dump generates binary dumps by default.

**Comment by jnv** [comment]
I work on this in the seeds branch, but Sequel fails to execute the script. This is probably due to Copy statement. Dump should use INSERT instead.
