### ISSUE TITLE
Remove tokens table

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#198]

**Comment by jirutka** [comment]
Why? Local tokens are long-living tokens used to access iCalendar export (typically from PIM applications).

**Comment by jnv** [comment]
I got it wrong, it should be other way around. Currently there is `tokens` table, which was a legacy way to access API without OAuth. I think we left it here for some legacy clients and because the auth server was undergoing some migration. So the plan here is to remove the legacy authentication via tokens and keep token per-user, which is autogenerated by DB.

**Comment by jirutka** [comment]
This is already done (b93cf8c5cd52a56628e035a23f36de4d2d5d1704).
