### ISSUE TITLE
Filter double lectures

### ISSUE THREAD

**Issue by dominikfryc** [cvut/sirius#251]
Almost all lectures (e.g., NI-PDP is, NI-DDW is not) are doubled at the same time but in different rooms. Could it be somehow filtered for at least export (iCal)? Most people have synchronization with Google Calendar, and it isn't enjoyable because it shows doubled every week for almost everyone.

**Comment by jirutka** [comment]
I’ve discussed it with our “Timetable Master” (Daniel Dombek). Unfortunately, it’s not a bug, it’s a feature. He informed both the teachers and the students about this oddity, so you should know about it already.

From ucitele-l:

> Někteří z vás, kteří mají učit v posluchárnách, si již mohli všimnout, že jim do rozvrhu přibývají kolizní okénka a mají "jednu přednášku na dvou místech současně", nelekejte se prosím. ICT opět plánuje zajištění streamovacích míst pro možný přesun z poslucháren do pohodlí budovy A (nebude to přesně 1:1 po místnostech, na oficiální informace ale vyčkejte) a já bych toto rád reflektoval oficiálně v rozvrhu - za cenu falešných kolizí v rozvrhu každý uvidíte, kdy máte kde streamovací zázemí a bude to i vyvěšené u místností.

And from my chat with Dan:

> místností-poslucháren je víc a jsou obsazeny nerovnoměrně, musel jsem to namapovat jinak než 1:1 místnost na místnost
> a někde to viset musí, explicitně,a současně nemůžu mazat ten kontaktní rozvrh, páč by to místo třeba mohl chtít někdo zabrat…
> a hlavně ve vedení máme jednotlivce, kteří se drží představy, že se učit kontaktně bude, takže ten kontaktní rozvrh nemůžu jen tak mazat…

I don’t like this solution at all, and I told it Dan today. There are better ways how to solve this problem. Unfortunately, I read e-mail from Dan in ucitele-l just today, after this issue, and he hadn’t consulted it with me before.

The duplicated events are identital, they differ only in the room. There’s no way how to determine from the event itself which one is for contact teaching (regular schedule) and which for streaming (i.e. useful only for teachers). You can create a list of “streaming rooms” and filter the events based on that, but not in Sirius (or fittable). I currently don’t have any capacity on the department to add some filter parameter into Sirius API and definitely don’t wanna implement any special-purpose hack to clean this duplication mess.

Sorry about that.
