### ISSUE TITLE
OAuth 2 authorization

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#42]
I'd hate for this to be a blocking feature, but here we go.

There are basically two ready-made libraries:

- [oauth2-provider](https://github.com/songkick/oauth2-provider/) – depends on ActiveRecord
- [rack-oauth2](https://github.com/nov/rack-oauth2)
- [omniauth-oauth2](https://github.com/intridea/omniauth-oauth2) – maybe with [warden](https://github.com/hassox/warden_omniauth)
- [warden-oauth2](https://github.com/airservice/warden-oauth2) ← this

Also a barebones client library:

- [oauth2](https://github.com/intridea/oauth2)

In both cases we'd probably need to add support for external OAAS. See [Zuul docs](https://github.com/cvut/zuul-oaas/blob/master/doc/provider-api.md).

**Comment by jirutka** [comment]
Basic support for OAuth 2.0 with remote OAAS has been implemented in 004c8a663efc237055bc4f466686223b6b409a52.
