### ISSUE TITLE
Custom  changes

### ISSUE THREAD

**Issue by hroncok** [cvut/sirius#56]
I didn't examine how sirius works, but I would really appreciate if I could log in to same page and set that I do not want this type of classes (e.g. lectures) of this subject shown in the calendar.
The ability to override KOS data (i.e. say I want to go to this lecture instead of that one), would be great as well. Currently, this blocks me from using the calendar, because I do not want all "garbage" classes or classes I don't in fact teach to be shown.

**Comment by jnv** [comment]
Why is this still open?
