### ISSUE TITLE
Use KOS code as a primary identifier for rooms

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#83]
Changed from #62. I suggest the following:

* KOS code (like `T9:355` etc.) will become a primary identifier for rooms, exposed for clients as a resource and also as an foreign key in other resources, i.e. schedule exceptions.
* KOS code will be the only supported identifier for v1 API, as there is no canonical source for the GTF codes yet.
* KOS code will be a part of the API specification so it is guaranteed for clients.
    * Should we eventually migrate to GTF codes, this will be included in the next API version.

**Comment by flexik** [comment]
Fixed in 6ee9a45a6a219dfc9e400b30cb2eb94176377819.

**Comment by jnv** [comment]
I guess there should be some migration for schedule exceptions too?

**Comment by flexik** [comment]
Well there is currently only one schedule exception in database which is referencing room id, so I have migrated it manually.
