### ISSUE TITLE
Expose ScheduleExceptions through an API

### ISSUE THREAD

**Issue by jnv** [cvut/sirius#84]

**Comment by jirutka** [comment]
@jnv Things are moving, we’ve started work on the front-end for “scheduler managers,” so we need this API ASAP.

**Comment by jnv** [comment]
This still depends on #83 because we need to expose natural IDs for room exceptions. However, I don't think we have any room exceptions for now.
The API still needs to be designed. @flexik, do you have any proposal on how to expose exceptions?

**Comment by jirutka** [comment]
@flexik, please document (here on the wiki?) types of schedule exceptions, allowed “scopes” (e.g. date, course, …) and attributes.

**Comment by jnv** [comment]
Okey, according to [ScheduleExceptionType](https://github.com/cvut/sirius/blob/247cc4df5dec414b4fa7819d7b541b456c9ac56c/lib/sirius/enums/schedule_exception_type.rb), we have:

* cancel,
* relative move (i.e. change of weekday),
* room change.

What attributes are required, shared and specific for each of these types?

**Comment by jirutka** [comment]
Closed by de2d53b1ea174491f63eb216c7db15122ddc40cc.
