### ISSUE TITLE
Events are not removed from Sirius when associated timetable slots are cancelled in KOS

### ISSUE THREAD

**Issue by hroncok** [cvut/sirius#90]
In my Sirius calendar (hroncmir), I see BI-3DT.1 practice (102) every Thursday 18:00 – 20:15.

 * I do not teach/study BI-3DT.1 this semester - see [my teacher's timetable](https://timetable.fit.cvut.cz/public/cz/ucitele/25/30/u2530206.html) and [my student's timetable](https://timetable.fit.cvut.cz/public/cz/studenti/25/30/s2530206.html) 
 * There is no class of BI-3DT.1 on Thursday - see [BI-3DT.1 timetable](https://timetable.fit.cvut.cz/public/cz/predmety/31/67/p3167206.html)

If I remember correctly, 102 was actually planned on Thursday (and I might as well be assigned as the teacher), but it was canceled last week before the beginning of the semester. Maybe you handle cancellation wrong?

**Comment by jnv** [comment]
Yeah, those events were not set as deleted in database. @flexik could you please take a look at it?

**Comment by jnv** [comment]
Bump this one to P1?

**Comment by jirutka** [comment]
Yeah. I hope that @flexik will have more free time next week...

**Comment by jirutka** [comment]
Another problem with incorrect data, probably cause by this issue.

BI-AAG, tutorial, 16.15 – Ondřej Guth _doesn’t_ teach this tutorial.

**Comment by jnv** [comment]
@flexik HALP!
