### ISSUE TITLE
API for faculty semester data

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#97]
Fittable and FEL needs data about semester per faculty like start and end date, hour starts etc.

**Comment by jirutka** [comment]
@jnv @flexik I really don’t like `/faculty_semester`, it’s  confusing for me. What do you think about `/faculty_params`? Is it better, or worse?

**Comment by jnv** [comment]
Well, can't we just use one word for that?

**Comment by jirutka** [comment]
Well, which one?

**Comment by jnv** [comment]
Let's see. There's [term](https://en.wikipedia.org/wiki/Academic_term) which is arguably a superset of semester (a “term” can be also trimester etc. depending on a school). You could also argue that each semester is specific for a given faculty, thus “faculty semester” is given by “semester” or “term”.

However, these data are specific for each faculty, so you can't avoid having faculty in name. But how about `faculty_term`? It keeps the original meaning but it's the shortest one.

**Comment by jirutka** [comment]
I'm sorry, I wanted to write `semester_params`, not `faculty_params` (see my PR)! I don't think it's needed to have _faculty_ in the name.

**Comment by jnv** [comment]
So why not just use `semester`?

**Comment by jirutka** [comment]
Hmm, good idea. What do you think, @flexik?

**Comment by jirutka** [comment]
The proposal is: `/semesters` and `/semesters/{faculty}-{semester}` (e.g. `/semesters/18000-B151`).

**Comment by jnv** [comment]
Semester's ID is unique across all faculties?

**Comment by jirutka** [comment]
Yes, of course it's the same. ;) See https://kosapi.fit.cvut.cz/projects/kosapi/wiki/SemesterFilter (KOSí kód).

**Comment by flexik** [comment]
This looks OK. By requiring faculty and semester id in the URL it is obvious that the provided semester data are related to a single faculty.

**Comment by jnv** [comment]
Well, the _proper_ way to implement this would be as a nested resource, i.e. `/faculty/18000/semester/B151`. But having either semester or faculty data alone is quite useless.

**Comment by jirutka** [comment]
@jnv I think that it’s _not_ a more proper way in this particular case.

**Comment by jirutka** [comment]
Another option would be this:

* `/semesters` … get all semesters for all faculties
* `/semesters/B151` ... get the specified semester for all faculties
* `/semesters/B151/18000` … get the specified semester on the specified faculty
