### ISSUE TITLE
Teachers should be allowed to view all calendars

### ISSUE THREAD

**Issue by jirutka** [cvut/sirius#99]
There are two possible roles - **teacher** and **student**.

- Teachers should be able to view all calendars and their own calendar is visible for everyone.
- Students can view their own calendar and calendars of rooms, courses and personal calendars of teachers.
- In case a person is both a student and a teacher, only the teacher role applies.

Roles should be retrieved from Umapi.

**Comment by flexik** [comment]
Any person with role `B-00000-ZAMESTNANEC` is considered to be a**teacher**.

**Comment by jnv** [comment]
What's the action plan for this? Do you want to import roles from Umapi on a daily basis or check them on the fly?

**Comment by jirutka** [comment]
Check them on the fly and cache the check result.

**Comment by jirutka** [comment]
I’ll create a special resource on Umapi to optimize role checking use case as much as I can.

**Comment by jnv** [comment]
This one is done, I guess.
